-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.3
-- Copyright 2000-2024 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE TABLE customers (
	customer_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	email varchar(100) NOT NULL,
	phone varchar(15),
	city varchar(50),
	created_date timestamp(0) DEFAULT statement_timestamp()
) ;
ALTER TABLE customers ADD UNIQUE (email);
ALTER TABLE customers ADD PRIMARY KEY (customer_id);
ALTER TABLE customers ALTER COLUMN customer_id SET NOT NULL;
ALTER TABLE customers ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE customers ALTER COLUMN last_name SET NOT NULL;
ALTER TABLE customers ALTER COLUMN email SET NOT NULL;


CREATE TABLE inventory (
	inventory_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	product_id bigint NOT NULL,
	quantity bigint NOT NULL,
	last_updated timestamp(0) DEFAULT statement_timestamp()
) ;
ALTER TABLE inventory ADD PRIMARY KEY (inventory_id);
ALTER TABLE inventory ALTER COLUMN inventory_id SET NOT NULL;
ALTER TABLE inventory ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE inventory ALTER COLUMN quantity SET NOT NULL;


CREATE TABLE orders (
	order_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	customer_id bigint NOT NULL,
	order_date timestamp(0) DEFAULT statement_timestamp(),
	status varchar(20) DEFAULT 'PENDING',
	total_amount double precision
) ;
ALTER TABLE orders ADD PRIMARY KEY (order_id);
ALTER TABLE orders ALTER COLUMN order_id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN customer_id SET NOT NULL;


CREATE TABLE order_items (
	item_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	order_id bigint NOT NULL,
	product_id bigint NOT NULL,
	quantity integer NOT NULL,
	unit_price double precision NOT NULL
) ;
ALTER TABLE order_items ADD PRIMARY KEY (item_id);
ALTER TABLE order_items ALTER COLUMN item_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN order_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN unit_price SET NOT NULL;


CREATE TABLE products (
	product_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	product_name varchar(100) NOT NULL,
	category varchar(50),
	price double precision NOT NULL,
	created_date timestamp(0) DEFAULT statement_timestamp()
) ;
ALTER TABLE products ADD PRIMARY KEY (product_id);
ALTER TABLE products ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE products ALTER COLUMN product_name SET NOT NULL;
ALTER TABLE products ALTER COLUMN price SET NOT NULL;
ALTER TABLE inventory ADD CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE order_items ADD CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE order_items ADD CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
